//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kp4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int id { get; set; }
        public Nullable<int> id_patient { get; set; }
        public Nullable<int> id_doctor { get; set; }
        public Nullable<int> id_schedule { get; set; }
        public Nullable<int> id_status { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual StatusEntry StatusEntry { get; set; }
    }
}
