//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kp4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int id { get; set; }
        public Nullable<int> id_doctor { get; set; }
        public Nullable<int> id_patient { get; set; }
        public Nullable<int> id_diagnosis { get; set; }
        public Nullable<int> id_medicament { get; set; }
        public string info { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Medicament Medicament { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
